import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // --- Stitch "Direct-to-Factory Landing (Light)" design system ---
        "background":                   "#faf9f7",
        "surface":                      "#faf9f7",
        "surface-bright":               "#faf9f7",
        "surface-dim":                  "#dadad8",
        "surface-tint":                 "#595e6d",
        "surface-container-lowest":     "#ffffff",
        "surface-container-low":        "#f4f3f1",
        "surface-container":            "#efeeec",
        "surface-container-high":       "#e9e8e6",
        "surface-container-highest":    "#e3e2e0",
        "surface-variant":              "#e3e2e0",
        "on-surface":                   "#1a1c1b",
        "on-surface-variant":           "#45464c",
        "on-background":                "#1a1c1b",
        "primary":                      "#030612",
        "on-primary":                   "#ffffff",
        "primary-container":            "#1a1f2c",
        "primary-fixed":                "#dee2f4",
        "primary-fixed-dim":            "#c2c6d8",
        "on-primary-fixed":             "#161b28",
        "on-primary-fixed-variant":     "#424655",
        "on-primary-container":         "#828697",
        "inverse-primary":              "#c2c6d8",
        "secondary":                    "#775a19",
        "on-secondary":                 "#ffffff",
        "secondary-container":          "#fed488",
        "on-secondary-container":       "#785a1a",
        "secondary-fixed":              "#ffdea5",
        "secondary-fixed-dim":          "#e9c176",
        "on-secondary-fixed":           "#261900",
        "on-secondary-fixed-variant":   "#5d4201",
        "tertiary":                     "#030810",
        "on-tertiary":                  "#ffffff",
        "tertiary-container":           "#192029",
        "tertiary-fixed":               "#dce3f0",
        "tertiary-fixed-dim":           "#c0c7d3",
        "on-tertiary-container":        "#808893",
        "on-tertiary-fixed":            "#151c25",
        "on-tertiary-fixed-variant":    "#404752",
        "outline":                      "#76777c",
        "outline-variant":              "#c6c6cc",
        "error":                        "#ba1a1a",
        "on-error":                     "#ffffff",
        "error-container":              "#ffdad6",
        "on-error-container":           "#93000a",
        "inverse-surface":              "#2f3130",
        "inverse-on-surface":           "#f1f1ef",
        // --- Customizer light-blue tokens (kept for customizer pages) ---
        "soft-blue":                    "#E8F4FC",
        "soft-blue-alt":                "#F0F7FF",
        "primary-blue":                 "#2563EB",
        "primary-blue-dark":            "#1D4ED8",
        "text-dark":                    "#1F2937",
        "border-light":                 "#E5E7EB",
        "border-blue":                  "#DBEAFE",
      },
      fontFamily: {
        headline: ["Noto Serif", "Georgia", "serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.25rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.5rem",
        "3xl":   "0.75rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
